cluster:
  name: grot-academy
alloy-metrics:
  enabled: true
alloy-logs:
  enabled: true
alloy-singleton:
  enabled: true
clusterMetrics:
  enabled: true
clusterEvents:
  enabled: true
annotationAutodiscovery:
  enabled: true
podLogs:
  enabled: true
nodeLogs:
  enabled: true
destinations:
  - name: grafana-hosted-metrics
    type: prometheus
    url: <grafana-hosted-metrics-url>
    auth:
      type: basic
      username: <grafana-username>
      password: <grafana-password>
  - name: grafana-hosted-logs
    type: loki
    url: <grafana-hosted-logs-url>
    auth:
      type: basic
      username: <grafana-username>
      password: <grafana-password>
