#!/bin/bash

curl -H "Content-Type: application/json" \
  --fail \
  -u "$1:$2" \
  -s -X POST "$3" \
  --data-raw "{\"streams\": [{ \"stream\": { \"grot_academy_check\": \"true\" }, \"values\": [ [ \"$(date +%s%N)\", \"never wield such power you forget to be polite\" ] ] }]}"
